# Generated by Django 4.2.5 on 2023-11-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customeruser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='last_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
