# Generated by Django 4.2.5 on 2023-11-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customeruser_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogincode',
            name='code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
