# Generated by Django 4.2.5 on 2023-11-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customerlogincode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlogincode',
            name='failed_tries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
