# Generated by Django 4.2.5 on 2023-11-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customerlogincode_last_try'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlogincode',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='customerlogincode',
            name='client_user_agent',
        ),
    ]
