# Generated by Django 4.2.5 on 2023-11-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customerlogincode_client_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloginsession',
            name='last_try',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
