# Generated by Django 4.2.5 on 2023-11-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customerloginsession_last_try'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloginsession',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.customeruser'),
        ),
    ]
