# Generated by Django 4.2.5 on 2023-11-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_icon',
            field=models.ImageField(default='product_default.png', upload_to='images/products_icon/'),
        ),
    ]
