# Generated by Django 4.2.5 on 2023-09-18 09:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='price', to='custom_menu.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='custom_menu.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guid',
            field=models.CharField(default=uuid.UUID('d9460efc-5067-43ea-a7f0-4d259a7ec2ca'), max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='quantity', to='custom_menu.product'),
        ),
    ]
