# Generated by Django 4.2.5 on 2023-09-18 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0002_alter_price_product_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='category_default.png', upload_to='images/categories/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product_default.png', upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='is_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='guid',
            field=models.CharField(default=uuid.UUID('7ac6dbc7-9184-4d9a-ae81-71f37131712b'), max_length=256, unique=True),
        ),
    ]
