# Generated by Django 4.2.5 on 2023-09-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0002_custommenucategory_custommenuproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommenuproduct',
            name='has_tax',
        ),
        migrations.RemoveField(
            model_name='custommenuproduct',
            name='used_products',
        ),
        migrations.AlterField(
            model_name='custommenuproduct',
            name='custom_menu_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='custom_menu.custommenucategory'),
        ),
        migrations.CreateModel(
            name='CustomMenuProductMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='product', to='custom_menu.product')),
            ],
        ),
        migrations.AddField(
            model_name='custommenuproduct',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='custom_menu.custommenuproductmap'),
        ),
    ]
