# Generated by Django 4.2.5 on 2023-09-19 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0003_category_category_image_product_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_amount',
            field=models.IntegerField(default=2, max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='english_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='persian_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='english_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='guid',
            field=models.CharField(default=uuid.UUID('1b80776b-4f51-4d86-b655-d87d43525dc0'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='persian_name',
            field=models.CharField(max_length=100),
        ),
    ]
