# Generated by Django 4.2.5 on 2023-09-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0003_remove_custommenuproduct_has_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommenuproductmap',
            name='product',
        ),
        migrations.AddField(
            model_name='custommenuproductmap',
            name='product',
            field=models.ManyToManyField(related_name='product', to='custom_menu.product'),
        ),
    ]
