# Generated by Django 4.2.5 on 2023-09-19 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0004_product_max_amount_alter_category_english_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='guid',
            field=models.CharField(default=uuid.UUID('3ce609e6-5105-4760-b3cf-398731578ac0'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_amount',
            field=models.IntegerField(default=2),
        ),
    ]
