# Generated by Django 4.2.5 on 2023-09-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0004_remove_custommenuproductmap_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommenuproduct',
            name='custom_menu_category',
        ),
        migrations.RemoveField(
            model_name='custommenuproduct',
            name='products',
        ),
        migrations.RemoveField(
            model_name='custommenuproductmap',
            name='product',
        ),
        migrations.DeleteModel(
            name='CustomMenuCategory',
        ),
        migrations.DeleteModel(
            name='CustomMenuProduct',
        ),
        migrations.DeleteModel(
            name='CustomMenuProductMap',
        ),
    ]
