# Generated by Django 4.2.5 on 2023-09-19 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0006_product_has_tax_alter_product_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='guid',
            field=models.CharField(default=uuid.UUID('69c98e99-36fd-44fb-a28d-b00d81976345'), max_length=100, unique=True),
        ),
    ]
