# Generated by Django 4.2.5 on 2023-09-20 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0007_alter_price_price_alter_product_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product', to='custom_menu.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guid',
            field=models.CharField(default=uuid.UUID('b02426e1-c07e-4e78-8caa-5cca33cd0010'), max_length=100, unique=True),
        ),
    ]
