# Generated by Django 4.2.5 on 2023-09-21 06:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0008_alter_product_category_alter_product_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='custom_menu.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guid',
            field=models.CharField(default=uuid.UUID('159336c6-c7fd-4aaf-b55d-91be09eae886'), max_length=100, unique=True),
        ),
    ]
