# Generated by Django 4.2.5 on 2023-10-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
