# Generated by Django 4.2.5 on 2023-10-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_menu', '0001_initial'),
        ('invoice', '0003_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='InvoiceDetail',
        ),
        migrations.AddField(
            model_name='invoiceproducts',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_products', to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceproductdetails',
            name='invoice_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_product_details', to='invoice.invoiceproducts'),
        ),
        migrations.AddField(
            model_name='invoiceproductdetails',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_product_detail_price', to='custom_menu.price'),
        ),
    ]
