# Generated by Django 4.2.5 on 2023-10-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_tempinvoice_tempinvoiceproducts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempinvoice',
            name='payment_type',
        ),
    ]
