# Generated by Django 4.2.5 on 2023-10-11 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0006_remove_tempinvoice_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='temp_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
